from __future__ import annotations

import hashlib
import sqlite3
from pathlib import Path


class AMSOnboardingPreviewError(ValueError):
    """The read-only AMS onboarding preview cannot be safely produced."""


class AMSOnboardingPreview:
    """Build a zero-write bridge preview for verified legacy AMS containers."""

    REQUIRED_SCHEMA = "019_flexible_spool_replacement.sql"
    PARENT_NUMBER = "THS-EQP-000001"
    ONBOARDING_EFFECTIVE_AT = "<actual future onboarding commit time>"
    GENERATED_UUID = "<generated by signed onboarding review>"
    SYSTEM_COMMIT_TIME = "<system commit time>"

    def __init__(self, database: Path | str):
        self.database = Path(database)

    def build(
        self,
        *,
        parent_serial: str = "01P00C511401400",
        ams_1_serial: str,
        ams_2_serial: str,
        ams_1_name: str = "Bambu Lab AMS 2 Pro - AMS 1",
        ams_2_name: str = "Bambu Lab AMS 2 Pro - AMS 2",
    ) -> dict:
        parent_serial = self._reported_serial(parent_serial, "P1S")
        serials = [
            self._reported_serial(ams_1_serial, "AMS 1"),
            self._reported_serial(ams_2_serial, "AMS 2"),
        ]
        names = [
            self._exact_name(ams_1_name, "AMS 1"),
            self._exact_name(ams_2_name, "AMS 2"),
        ]
        if self._normalized(serials[0]) == self._normalized(serials[1]):
            raise AMSOnboardingPreviewError("reported AMS serials are duplicates")
        if self._normalized(names[0]) == self._normalized(names[1]):
            raise AMSOnboardingPreviewError("proposed AMS names are duplicates")
        if not self.database.is_file():
            raise AMSOnboardingPreviewError("production database was not found")

        before = self._sha256()
        db = sqlite3.connect(f"{self.database.resolve().as_uri()}?mode=ro", uri=True)
        db.row_factory = sqlite3.Row
        db.execute("PRAGMA query_only=ON")
        try:
            self._validate_database(db)
            parent = self._parent(db)
            self._reject_parent_serial_conflict(db, parent, parent_serial, serials)
            manufacturer = self._manufacturer(db)
            equipment_type, subtype = self._type_rows(db)
            self._reject_duplicates(db, serials, names)
            legacy_units = self._legacy_units(db)
            next_numbers = self._next_numbers(db, 2)
            counts = self._counts(db)
            maintenance_assets = self._maintenance_assets(db)
            maintenance_number = self._next_maintenance_number(db)
            repair_part = self._repair_part_preview(db)
            units = []
            for index, legacy in enumerate(legacy_units):
                units.append(
                    self._unit_preview(
                        db=db,
                        legacy=legacy,
                        equipment_number=next_numbers[index],
                        display_name=names[index],
                        serial=serials[index],
                        parent=parent,
                        manufacturer=manufacturer,
                        equipment_type=equipment_type,
                        subtype=subtype,
                        maintenance_asset=maintenance_assets[legacy["id"]],
                        maintenance_number=maintenance_number,
                        repair_part=repair_part,
                    )
                )
            protected = self._protected_fingerprints(db)
            integrity = db.execute("PRAGMA quick_check").fetchone()[0]
            foreign_keys = len(db.execute("PRAGMA foreign_key_check").fetchall())
        finally:
            db.close()
        after = self._sha256()
        if before != after:
            raise AMSOnboardingPreviewError("database changed during read-only preview")

        return {
            "mode": "zero-write",
            "database": str(self.database.resolve()),
            "schema": 19,
            "latest_migration": self.REQUIRED_SCHEMA,
            "sha256_before": before,
            "sha256_after": after,
            "database_unchanged": True,
            "integrity": integrity,
            "foreign_key_violations": foreign_keys,
            "parent": parent,
            "parent_serial_correction": {
                "table": "equipment_registry",
                "operation": "UPDATE",
                "id": parent["id"],
                "equipment_number": parent["equipment_number"],
                "manufacturer_serial_number_before": parent[
                    "manufacturer_serial_number"
                ],
                "manufacturer_serial_number_after": parent_serial,
                "state_version_before": parent["state_version"],
                "state_version_after": parent["state_version"] + 1,
                "history_action": "update_facts",
                "audit_event": "update_equipment_facts",
            },
            "before_counts": counts,
            "units": units,
            "protected_fingerprints": protected,
            "expected_row_changes": self._expected_row_changes(
                units, parent, repair_part
            ),
            "production_ready": False,
            "architecture_blockers": [
                (
                    "The existing maintenance record can scope the restriction to "
                    "Slot 2 / A2 in symptoms, corrective action, and notes, but the "
                    "inventory loading service does not enforce maintenance-note text."
                ),
                (
                    "The current service has no single atomic workflow for P1S fact "
                    "correction, two registrations, relationships, legacy bridges, "
                    "the AMS 1 maintenance link, record, readiness update, repair-part "
                    "inventory, and history."
                ),
            ],
            "maintenance_representation": units[0]["maintenance_issue"],
            "repair_part": repair_part,
            "confirmation_questions": [
                (
                    "Confirm the feeder unit's current physical storage location. "
                    "THS Bambu Maintenance Cabinet does not exist in production and "
                    "no location row is proposed."
                ),
                (
                    "Authorize a narrow atomic onboarding service checkpoint before "
                    "any production commit."
                ),
            ],
            "design_notes": {
                "slots": (
                    "All eight equipment_slots rows already exist and remain authoritative. "
                    "They are adopted through one-to-one legacy-container links, not recreated."
                ),
                "filament": (
                    "Existing ams_assignments continue to reference the same slot IDs. "
                    "No assignment, spool, quantity, transaction, or audit history is rewritten."
                ),
                "readiness": (
                    "AMS 1 is Degraded with an in-progress maintenance fault and "
                    "Monitor during printing readiness; AMS 2 remains unlinked so its "
                    "readiness projects Unknown until inspection."
                ),
                "provenance": (
                    "No purchase or receiving link is proposed. Any later provenance remains inert."
                ),
                "repair_part": (
                    "The boxed feeder is available candidate inventory only. It is not "
                    "reserved, issued, consumed, installed, or recorded as a completed repair."
                ),
            },
        }

    def _unit_preview(
        self,
        *,
        db,
        legacy,
        equipment_number,
        display_name,
        serial,
        parent,
        manufacturer,
        equipment_type,
        subtype,
        maintenance_asset,
        maintenance_number,
        repair_part,
    ):
        slots = [
            dict(row)
            for row in db.execute(
                """
                SELECT es.id slot_id,es.slot_number,es.location_id,l.name location_name,
                       aa.id assignment_id,aa.instance_id,aa.loaded_at,
                       ii.permanent_id spool_number,ii.state spool_state,
                       ii.remaining_quantity,m.name manufacturer,
                       ci.product_line,ci.variant color
                FROM equipment_slots es
                JOIN locations l ON l.id=es.location_id
                LEFT JOIN ams_assignments aa
                  ON aa.slot_id=es.id AND aa.unloaded_at IS NULL
                LEFT JOIN inventory_instances ii ON ii.id=aa.instance_id
                LEFT JOIN catalog_items ci ON ci.id=ii.catalog_item_id
                LEFT JOIN manufacturers m ON m.id=ci.manufacturer_id
                WHERE es.equipment_id=? ORDER BY es.slot_number
                """,
                (legacy["id"],),
            )
        ]
        physical = self._physical_truth(legacy["name"])
        for slot in slots:
            expected = physical[slot["slot_number"]]
            stored = slot["color"]
            slot.update(
                {
                    "bambu_designation": expected["designation"],
                    "confirmed_physical_color": expected["color"],
                    "confirmed_availability": expected["availability"],
                    "physical_match": self._slot_matches(stored, expected["color"]),
                }
            )
        maintenance_issue = None
        if legacy["name"] == "AMS 1":
            maintenance_issue = {
                "maintenance_asset_link": {
                    "equipment_id": "<allocated THS-EQP-000002 row ID>",
                    "maintenance_asset_id": maintenance_asset["id"],
                    "linked_by": "Cowboy",
                    "linked_at": self.SYSTEM_COMMIT_TIME,
                },
                "maintenance_asset_update": {
                    "id": maintenance_asset["id"],
                    "readiness_state_before": maintenance_asset["readiness_state"],
                    "readiness_state_after": "monitor_during_printing",
                    "updated_at": self.SYSTEM_COMMIT_TIME,
                    "meaning": (
                        "AMS remains usable with Slot 2 restricted and Slots 1, 3, 4 available."
                    ),
                },
                "maintenance_record": {
                    "id": "<allocated at commit>",
                    "event_number": maintenance_number,
                    "asset_id": maintenance_asset["id"],
                    "event_type": "fault_discovered",
                    "status": "in_progress",
                    "severity": "high",
                    "discovered_at": self.ONBOARDING_EFFECTIVE_AT,
                    "due_at": None,
                    "completed_at": None,
                    "symptoms": (
                        "Affected component: Slot 2 / A2. Reported symptom: "
                        "the feeder/roller becomes loud and may lock."
                    ),
                    "likely_cause": None,
                    "corrective_action": (
                        "Required resolution: inspect, repair, and function-test "
                        "Slot 2 / A2 before returning it to service."
                    ),
                    "parts_required": (
                        f"Available candidate part: {repair_part['candidate_reference']} "
                        f"Bambu Lab AMS 2 Pro Feeder Unit, model SA403-V1, "
                        f"UPC 6937285503237. Not reserved, issued, consumed, or installed."
                    ),
                    "parts_used": None,
                    "notes": (
                        "Restriction: Slot 2 / A2 is Out of service — do not load "
                        "filament. Slot 4 / A4 remains in service; it has historically "
                        "rewound faster than the spool and should be monitored. Slot 4 "
                        "is currently loaded with Cocoa Brown and functioning."
                    ),
                    "related_print_id": None,
                    "unattended_printing_allowed": True,
                    "created_by": "Cowboy",
                    "created_at": self.SYSTEM_COMMIT_TIME,
                    "updated_at": self.SYSTEM_COMMIT_TIME,
                },
                "maintenance_history": {
                    "action_type": "record_fault",
                    "previous_status": None,
                    "new_status": "in_progress",
                    "previous_readiness_state": maintenance_asset["readiness_state"],
                    "new_readiness_state": "monitor_during_printing",
                    "actor": "Cowboy",
                    "occurred_at": self.SYSTEM_COMMIT_TIME,
                    "immutable": True,
                },
                "slot_2_assignment_precondition": {
                    "slot_id": 2,
                    "must_be_empty": True,
                    "create_assignment": False,
                },
            }
        return {
            "registry_record": {
                "id": "<allocated at commit>",
                "equipment_uuid": self.GENERATED_UUID,
                "equipment_number": equipment_number,
                "display_name": display_name,
                "equipment_type_id": equipment_type["id"],
                "equipment_type": equipment_type["type_code"],
                "equipment_subtype_id": subtype["id"],
                "equipment_subtype": subtype["subtype_code"],
                "manufacturer_id": manufacturer["id"],
                "manufacturer": manufacturer["name"],
                "model": "AMS 2 Pro",
                "manufacturer_serial_number": serial,
                "ths_asset_identifier": None,
                "current_location_id": None,
                "lifecycle_state": "installed",
                "operational_status": (
                    "degraded" if legacy["name"] == "AMS 1" else "operating"
                ),
                "installed_at": None,
                "commissioned_at": None,
                "retired_at": None,
                "disposed_at": None,
                "notes": (
                    f"Bambu Studio designation {'A' if legacy['name'] == 'AMS 1' else 'B'}. "
                    f"Linked to legacy {legacy['name']} container; existing slot "
                    "and filament assignment history preserved."
                ),
                "state_version": 1,
                "created_by": "Cowboy",
                "created_at": self.SYSTEM_COMMIT_TIME,
                "updated_at": self.SYSTEM_COMMIT_TIME,
            },
            "relationship": {
                "child_equipment_id": "<allocated registry row ID>",
                "parent_equipment_id": parent["id"],
                "parent_equipment_number": parent["equipment_number"],
                "relationship_type": "attached_to",
                "state_version": 1,
                "effective_at": self.ONBOARDING_EFFECTIVE_AT,
                "updated_at": self.SYSTEM_COMMIT_TIME,
            },
            "legacy_container_link": {
                "equipment_id": "<allocated registry row ID>",
                "legacy_equipment_id": legacy["id"],
                "legacy_name": legacy["name"],
                "linked_by": "Cowboy",
                "linked_at": self.SYSTEM_COMMIT_TIME,
            },
            "existing_maintenance_asset": maintenance_asset,
            "maintenance_link_proposed": legacy["name"] == "AMS 1",
            "maintenance_issue": maintenance_issue,
            "existing_slots_unchanged": slots,
            "expected_audit": [
                "register_equipment",
                "attach_equipment_relationship",
                "link_legacy_equipment_container",
            ],
            "expected_immutable_history": [
                "equipment_history.register",
                "equipment_relationship_history.attach",
            ],
        }

    def _validate_database(self, db):
        latest = db.execute(
            "SELECT name FROM schema_migrations ORDER BY applied_at DESC,name DESC LIMIT 1"
        ).fetchone()
        count = db.execute("SELECT COUNT(*) FROM schema_migrations").fetchone()[0]
        if count != 19 or not latest or latest[0] != self.REQUIRED_SCHEMA:
            raise AMSOnboardingPreviewError("production schema is not exactly 19")
        if db.execute("PRAGMA quick_check").fetchone()[0] != "ok":
            raise AMSOnboardingPreviewError("database integrity check failed")
        if db.execute("PRAGMA foreign_key_check").fetchone():
            raise AMSOnboardingPreviewError("database has foreign-key violations")

    def _parent(self, db):
        rows = db.execute(
            """
            SELECT er.id,er.equipment_uuid,er.equipment_number,er.display_name,
                   er.model,er.manufacturer_serial_number,er.lifecycle_state,
                   er.operational_status,er.state_version
            FROM equipment_registry er
            JOIN equipment_types et ON et.id=er.equipment_type_id
            LEFT JOIN manufacturers m ON m.id=er.manufacturer_id
            WHERE er.equipment_number=? AND et.type_code='printer'
              AND m.name='Bambu Lab' AND er.model='P1S'
            """,
            (self.PARENT_NUMBER,),
        ).fetchall()
        if len(rows) != 1:
            raise AMSOnboardingPreviewError("exact P1S parent equipment record was not found")
        return dict(rows[0])

    def _reject_parent_serial_conflict(self, db, parent, parent_serial, child_serials):
        if parent["manufacturer_serial_number"] not in (None, parent_serial):
            raise AMSOnboardingPreviewError(
                "P1S manufacturer serial conflicts with confirmed physical truth"
            )
        all_serials = [parent_serial, *child_serials]
        if len({self._normalized(value) for value in all_serials}) != len(all_serials):
            raise AMSOnboardingPreviewError("confirmed equipment serials are duplicates")
        duplicate = db.execute(
            """
            SELECT equipment_number FROM equipment_registry
            WHERE id<>? AND manufacturer_serial_number IS NOT NULL
              AND lower(trim(manufacturer_serial_number))=lower(trim(?))
            """,
            (parent["id"], parent_serial),
        ).fetchone()
        if duplicate:
            raise AMSOnboardingPreviewError(
                "confirmed P1S manufacturer serial is already registered"
            )

    @staticmethod
    def _manufacturer(db):
        rows = db.execute(
            "SELECT id,name FROM manufacturers WHERE name='Bambu Lab' AND archived_at IS NULL"
        ).fetchall()
        if len(rows) != 1:
            raise AMSOnboardingPreviewError("exact Bambu Lab manufacturer is unavailable")
        return dict(rows[0])

    @staticmethod
    def _type_rows(db):
        equipment_type = db.execute(
            "SELECT * FROM equipment_types WHERE type_code='ams_unit' AND active=1"
        ).fetchone()
        subtype = db.execute(
            """
            SELECT es.* FROM equipment_subtypes es
            JOIN equipment_types et ON et.id=es.equipment_type_id
            WHERE et.type_code='ams_unit' AND es.subtype_code='bambu_ams' AND es.active=1
            """
        ).fetchone()
        if not equipment_type or not subtype:
            raise AMSOnboardingPreviewError("AMS equipment type configuration is unavailable")
        return dict(equipment_type), dict(subtype)

    def _legacy_units(self, db):
        rows = [
            dict(row)
            for row in db.execute(
                """
                SELECT e.* FROM equipment e
                WHERE e.equipment_type='AMS' AND e.archived_at IS NULL
                ORDER BY e.name,e.id
                """
            )
        ]
        if [row["name"] for row in rows] != ["AMS 1", "AMS 2"]:
            raise AMSOnboardingPreviewError("legacy AMS containers are not exactly AMS 1 and AMS 2")
        for row in rows:
            slots = [
                item[0]
                for item in db.execute(
                    "SELECT slot_number FROM equipment_slots WHERE equipment_id=? ORDER BY slot_number",
                    (row["id"],),
                )
            ]
            if row["slot_count"] != 4 or slots != [1, 2, 3, 4]:
                raise AMSOnboardingPreviewError(
                    f"{row['name']} does not have exactly unique slots 1 through 4"
                )
            if db.execute(
                "SELECT 1 FROM equipment_legacy_container_links WHERE legacy_equipment_id=?",
                (row["id"],),
            ).fetchone():
                raise AMSOnboardingPreviewError(
                    f"{row['name']} is already linked to Equipment Registry"
                )
        return rows

    def _reject_duplicates(self, db, serials, names):
        existing_serials = {
            self._normalized(row[0])
            for row in db.execute(
                """
                SELECT manufacturer_serial_number FROM equipment_registry
                WHERE manufacturer_serial_number IS NOT NULL
                """
            )
        }
        if any(self._normalized(value) in existing_serials for value in serials):
            raise AMSOnboardingPreviewError("reported manufacturer serial is already registered")
        existing_names = {
            self._normalized(row[0])
            for row in db.execute("SELECT display_name FROM equipment_registry")
        }
        if any(self._normalized(value) in existing_names for value in names):
            raise AMSOnboardingPreviewError("proposed AMS display name is already registered")

    @staticmethod
    def _next_numbers(db, count):
        maximum = 0
        for row in db.execute("SELECT equipment_number FROM equipment_registry"):
            try:
                maximum = max(maximum, int(row[0].removeprefix("THS-EQP-")))
            except ValueError as exc:
                raise AMSOnboardingPreviewError(
                    "existing equipment number sequence is invalid"
                ) from exc
        return [f"THS-EQP-{maximum + offset:06d}" for offset in range(1, count + 1)]

    @staticmethod
    def _counts(db):
        return dict(
            db.execute(
                """
                SELECT
                  (SELECT COUNT(*) FROM equipment_registry) equipment_registry,
                  (SELECT COUNT(*) FROM equipment_history) equipment_history,
                  (SELECT COUNT(*) FROM equipment_relationship_state) relationship_state,
                  (SELECT COUNT(*) FROM equipment_relationship_history) relationship_history,
                  (SELECT COUNT(*) FROM equipment_legacy_container_links) legacy_links,
                  (SELECT COUNT(*) FROM equipment_slots) equipment_slots,
                  (SELECT COUNT(*) FROM ams_assignments) all_assignments,
                  (SELECT COUNT(*) FROM ams_assignments WHERE unloaded_at IS NULL) active_assignments,
                  (SELECT COUNT(*) FROM audit_events WHERE module='equipment-registry') registry_audits
                """
            ).fetchone()
        )

    @staticmethod
    def _maintenance_assets(db):
        rows = [
            dict(row)
            for row in db.execute(
                """
                SELECT ma.*,e.name legacy_equipment_name
                FROM maintenance_assets ma
                JOIN equipment e ON e.id=ma.equipment_id
                WHERE ma.asset_type='shop_equipment' AND e.equipment_type='AMS'
                ORDER BY e.id
                """
            )
        ]
        result = {row["equipment_id"]: row for row in rows}
        if set(result) != {1, 2}:
            raise AMSOnboardingPreviewError(
                "legacy AMS maintenance assets are not exactly mapped"
            )
        return result

    @staticmethod
    def _next_maintenance_number(db):
        maximum = db.execute(
            """
            SELECT MAX(CAST(SUBSTR(event_number,LENGTH('THS-MNT')+2) AS INTEGER))
            FROM (
              SELECT event_number FROM maintenance_events
              UNION ALL SELECT event_number FROM maintenance_records
            ) WHERE event_number LIKE 'THS-MNT-%'
            """
        ).fetchone()[0] or 0
        return f"THS-MNT-{maximum + 1:06d}"

    @staticmethod
    def _protected_fingerprints(db):
        result = {}
        for table in (
            "equipment",
            "equipment_slots",
            "ams_assignments",
            "inventory_instances",
            "inventory_transactions",
            "transaction_lines",
        ):
            rows = db.execute(f"SELECT * FROM {table} ORDER BY rowid").fetchall()
            encoded = repr([tuple(row) for row in rows]).encode()
            result[table] = hashlib.sha256(encoded).hexdigest().upper()
        return result

    @staticmethod
    def _expected_row_changes(units, parent, repair_part):
        rows = []
        for unit in units:
            number = unit["registry_record"]["equipment_number"]
            rows.extend(
                [
                    {"table": "equipment_registry", "operation": "INSERT", "equipment": number},
                    {"table": "equipment_history", "operation": "INSERT", "equipment": number},
                    {"table": "audit_events", "operation": "INSERT", "equipment": number,
                     "event_type": "register_equipment"},
                    {"table": "equipment_relationship_state", "operation": "INSERT",
                     "equipment": number},
                    {"table": "equipment_relationship_history", "operation": "INSERT",
                     "equipment": number, "action_type": "attach"},
                    {"table": "audit_events", "operation": "INSERT", "equipment": number,
                     "event_type": "attach_equipment_relationship"},
                    {"table": "equipment_legacy_container_links", "operation": "INSERT",
                     "equipment": number},
                    {"table": "audit_events", "operation": "INSERT", "equipment": number,
                     "event_type": "link_legacy_equipment_container"},
                ]
            )
        rows.extend(
            [
                {
                    "table": "equipment_history",
                    "operation": "INSERT",
                    "equipment": parent["equipment_number"],
                    "action_type": "update_facts",
                },
                {
                    "table": "audit_events",
                    "operation": "INSERT",
                    "equipment": parent["equipment_number"],
                    "event_type": "update_equipment_facts",
                },
            ]
        )
        ams_1 = units[0]
        rows.extend(
            [
                {
                    "table": "equipment_maintenance_asset_links",
                    "operation": "INSERT",
                    "equipment": ams_1["registry_record"]["equipment_number"],
                    "maintenance_asset_id": ams_1["existing_maintenance_asset"]["id"],
                },
                {
                    "table": "maintenance_records",
                    "operation": "INSERT",
                    "equipment": ams_1["registry_record"]["equipment_number"],
                    "event_number": ams_1["maintenance_issue"]["maintenance_record"][
                        "event_number"
                    ],
                },
                {
                    "table": "maintenance_history",
                    "operation": "INSERT",
                    "equipment": ams_1["registry_record"]["equipment_number"],
                    "action_type": "record_fault",
                },
            ]
        )
        if not repair_part["matching_part_found"]:
            rows.extend(
                [
                    {
                        "table": "item_types",
                        "operation": "INSERT",
                        "item_type": "Printer Part",
                    },
                    {
                        "table": "audit_events",
                        "operation": "INSERT",
                        "event_type": "create_item_type",
                        "entity": "Printer Part",
                    },
                    {
                        "table": "catalog_items",
                        "operation": "INSERT",
                        "product": repair_part["product_name"],
                    },
                    {
                        "table": "audit_events",
                        "operation": "INSERT",
                        "event_type": "create_catalog_item",
                        "entity": repair_part["product_name"],
                    },
                    {
                        "table": "inventory_instances",
                        "operation": "INSERT",
                        "instance": repair_part["proposed_instance"]["permanent_id"],
                    },
                    {
                        "table": "inventory_transactions",
                        "operation": "INSERT",
                        "transaction_type": "add",
                        "instance": repair_part["proposed_instance"]["permanent_id"],
                    },
                    {
                        "table": "transaction_lines",
                        "operation": "INSERT",
                        "instance": repair_part["proposed_instance"]["permanent_id"],
                    },
                    {
                        "table": "audit_events",
                        "operation": "INSERT",
                        "event_type": "add_individual_instance",
                        "entity": repair_part["proposed_instance"]["permanent_id"],
                    },
                ]
            )
        return {
            "inserts": rows,
            "updates": [
                {
                    "table": "equipment_registry",
                    "equipment": parent["equipment_number"],
                    "fields": ["manufacturer_serial_number", "state_version", "updated_at"],
                },
                {
                    "table": "maintenance_assets",
                    "equipment": ams_1["registry_record"]["equipment_number"],
                    "maintenance_asset_id": ams_1["existing_maintenance_asset"]["id"],
                    "fields": ["readiness_state", "updated_at"],
                },
            ],
            "deletes": [],
            "slot_rows_created": 0,
            "slot_rows_changed": 0,
            "assignment_rows_changed": 0,
            "total_insert_rows": len(rows),
            "blocked_required_rows": 0,
        }

    @staticmethod
    def _repair_part_preview(db):
        product_name = "Bambu Lab AMS 2 Pro Feeder Unit"
        model = "SA403-V1"
        upc = "6937285503237"
        matches = [
            dict(row)
            for row in db.execute(
                """
                SELECT DISTINCT ci.id catalog_item_id,ci.name,ci.product_line,
                       ci.variant,ci.manufacturer_sku,ci.notes catalog_notes,
                       ii.id instance_id,ii.permanent_id,ii.state,ii.condition,
                       ii.location_id,ii.notes instance_notes
                FROM catalog_items ci
                LEFT JOIN inventory_instances ii ON ii.catalog_item_id=ci.id
                LEFT JOIN catalog_item_attribute_values av
                  ON av.catalog_item_id=ci.id
                WHERE lower(trim(ci.name))=lower(trim(?))
                   OR lower(trim(COALESCE(ci.manufacturer_sku,'')))=lower(trim(?))
                   OR lower(trim(COALESCE(ci.variant,'')))=lower(trim(?))
                   OR instr(lower(COALESCE(ci.notes,'')),lower(?))>0
                   OR instr(lower(COALESCE(ii.notes,'')),lower(?))>0
                   OR instr(lower(COALESCE(av.text_value,'')),lower(?))>0
                ORDER BY ci.id,ii.id
                """,
                (product_name, model, model, upc, upc, upc),
            )
        ]
        purchase_matches = [
            dict(row)
            for row in db.execute(
                """
                SELECT id,description,vendor_sku,catalog_item_id,quantity_ordered,notes
                FROM purchase_order_lines
                WHERE lower(trim(description))=lower(trim(?))
                   OR lower(trim(COALESCE(vendor_sku,'')))=lower(trim(?))
                   OR instr(lower(COALESCE(notes,'')),lower(?))>0
                ORDER BY id
                """,
                (product_name, model, upc),
            )
        ]
        cabinet = db.execute(
            """
            SELECT id,parent_id,name,kind,archived_at FROM locations
            WHERE lower(trim(name))=lower(trim(?))
            """,
            ("THS Bambu Maintenance Cabinet",),
        ).fetchall()
        if len(cabinet) > 1:
            raise AMSOnboardingPreviewError(
                "multiple THS Bambu Maintenance Cabinet locations exist"
            )
        existing_prefix = db.execute(
            "SELECT id,name,tracking_method,id_prefix FROM item_types WHERE id_prefix='THS-PART'"
        ).fetchone()
        next_number = 1
        if existing_prefix:
            for row in db.execute(
                "SELECT permanent_id FROM inventory_instances WHERE permanent_id LIKE 'THS-PART-%'"
            ):
                try:
                    next_number = max(
                        next_number,
                        int(row[0].removeprefix("THS-PART-")) + 1,
                    )
                except ValueError as exc:
                    raise AMSOnboardingPreviewError(
                        "existing printer-part permanent ID sequence is invalid"
                    ) from exc
        matching_part_found = bool(matches)
        candidate_reference = (
            matches[0]["permanent_id"]
            if matching_part_found and matches[0]["permanent_id"]
            else (
                f"catalog item {matches[0]['catalog_item_id']}"
                if matching_part_found
                else f"THS-PART-{next_number:06d}"
            )
        )
        return {
            "product_name": product_name,
            "model": model,
            "upc": upc,
            "quantity": 1,
            "condition": "New/boxed",
            "intended_use": "AMS 1 Slot 2 / A2 feeder repair",
            "installation_state": "Not installed",
            "catalog_or_inventory_matches": matches,
            "purchase_line_matches": purchase_matches,
            "matching_part_found": matching_part_found,
            "candidate_reference": candidate_reference,
            "duplicate_creation_allowed": False,
            "proposed_item_type": None
            if matching_part_found
            else {
                "name": "Printer Part",
                "category": "3D Printing",
                "tracking_method": "individual",
                "id_prefix": "THS-PART",
                "default_unit": "ea",
            },
            "proposed_catalog_item": None
            if matching_part_found
            else {
                "manufacturer": "Bambu Lab",
                "name": product_name,
                "product_line": "AMS 2 Pro",
                "variant": model,
                "manufacturer_sku": model,
                "base_unit": "ea",
                "notes": f"UPC {upc}. Candidate maintenance part.",
            },
            "proposed_instance": None
            if matching_part_found
            else {
                "permanent_id": f"THS-PART-{next_number:06d}",
                "state": "sealed",
                "condition": "new/boxed",
                "location_id": cabinet[0]["id"] if cabinet else None,
                "location_name": cabinet[0]["name"] if cabinet else None,
                "location_confirmation_required": not bool(cabinet),
                "original_quantity": 1,
                "remaining_quantity": 1,
                "unit": "ea",
                "verified": True,
                "installed": False,
                "reserved": False,
                "issued": False,
                "consumed": False,
                "notes": (
                    f"UPC {upc}. Available candidate for AMS 1 Slot 2 / A2 feeder "
                    "repair. Not installed, reserved, issued, or consumed."
                ),
            },
            "cabinet_location_match": dict(cabinet[0]) if cabinet else None,
            "storage_confirmation_required": not bool(cabinet),
            "future_decision": (
                "After Slot 2 is repaired and function-tested, decide whether to "
                "purchase one additional SA403-V1 as a sealed shelf spare."
            ),
        }

    @staticmethod
    def _physical_truth(legacy_name):
        if legacy_name == "AMS 1":
            return {
                1: {"designation": "A1", "color": "Purple", "availability": "usable"},
                2: {
                    "designation": "A2",
                    "color": None,
                    "availability": "empty_out_of_service_do_not_load",
                },
                3: {"designation": "A3", "color": "Hot Pink", "availability": "usable"},
                4: {
                    "designation": "A4",
                    "color": "Cocoa Brown",
                    "availability": "usable_monitor",
                },
            }
        return {
            1: {"designation": "B1", "color": "Black", "availability": "usable"},
            2: {"designation": "B2", "color": "Orange", "availability": "usable"},
            3: {"designation": "B3", "color": "Blue", "availability": "usable"},
            4: {"designation": "B4", "color": "White", "availability": "usable"},
        }

    @staticmethod
    def _slot_matches(stored_color, physical_color):
        if stored_color is None or physical_color is None:
            return stored_color is physical_color
        stored = " ".join(stored_color.casefold().split())
        physical = " ".join(physical_color.casefold().split())
        compatible = {
            ("cyan", "blue"),
            ("jade white", "white"),
        }
        return stored == physical or (stored, physical) in compatible

    def _sha256(self):
        return hashlib.sha256(self.database.read_bytes()).hexdigest().upper()

    @staticmethod
    def _reported_serial(value, label):
        if not isinstance(value, str) or not value:
            raise AMSOnboardingPreviewError(f"{label} reported serial is required")
        if value != value.strip():
            raise AMSOnboardingPreviewError(
                f"{label} reported serial has unverified leading or trailing whitespace"
            )
        if any(ord(character) < 32 for character in value):
            raise AMSOnboardingPreviewError(f"{label} reported serial contains control characters")
        return value

    @staticmethod
    def _exact_name(value, label):
        if not isinstance(value, str) or not value or value != value.strip():
            raise AMSOnboardingPreviewError(f"{label} proposed display name is invalid")
        return value

    @staticmethod
    def _normalized(value):
        return " ".join(value.casefold().split())
