from __future__ import annotations

import hashlib
import sqlite3
from pathlib import Path


class AMSOnboardingPreviewError(ValueError):
    """The read-only AMS onboarding preview cannot be safely produced."""


class AMSOnboardingPreview:
    """Build a zero-write bridge preview for verified legacy AMS containers."""

    REQUIRED_SCHEMA = "019_flexible_spool_replacement.sql"
    PARENT_NUMBER = "THS-EQP-000001"
    UNCONFIRMED_EFFECTIVE_AT = "<Cowboy-confirmed attachment effective time>"
    GENERATED_UUID = "<generated by signed onboarding review>"
    SYSTEM_COMMIT_TIME = "<system commit time>"

    def __init__(self, database: Path | str):
        self.database = Path(database)

    def build(
        self,
        *,
        ams_1_serial: str,
        ams_2_serial: str,
        ams_1_name: str = "Bambu Lab AMS 2 Pro - AMS 1",
        ams_2_name: str = "Bambu Lab AMS 2 Pro - AMS 2",
    ) -> dict:
        serials = [
            self._reported_serial(ams_1_serial, "AMS 1"),
            self._reported_serial(ams_2_serial, "AMS 2"),
        ]
        names = [
            self._exact_name(ams_1_name, "AMS 1"),
            self._exact_name(ams_2_name, "AMS 2"),
        ]
        if self._normalized(serials[0]) == self._normalized(serials[1]):
            raise AMSOnboardingPreviewError("reported AMS serials are duplicates")
        if self._normalized(names[0]) == self._normalized(names[1]):
            raise AMSOnboardingPreviewError("proposed AMS names are duplicates")
        if not self.database.is_file():
            raise AMSOnboardingPreviewError("production database was not found")

        before = self._sha256()
        db = sqlite3.connect(f"{self.database.resolve().as_uri()}?mode=ro", uri=True)
        db.row_factory = sqlite3.Row
        db.execute("PRAGMA query_only=ON")
        try:
            self._validate_database(db)
            parent = self._parent(db)
            manufacturer = self._manufacturer(db)
            equipment_type, subtype = self._type_rows(db)
            self._reject_duplicates(db, serials, names)
            legacy_units = self._legacy_units(db)
            next_numbers = self._next_numbers(db, 2)
            counts = self._counts(db)
            units = []
            for index, legacy in enumerate(legacy_units):
                units.append(
                    self._unit_preview(
                        db=db,
                        legacy=legacy,
                        equipment_number=next_numbers[index],
                        display_name=names[index],
                        serial=serials[index],
                        parent=parent,
                        manufacturer=manufacturer,
                        equipment_type=equipment_type,
                        subtype=subtype,
                    )
                )
            protected = self._protected_fingerprints(db)
            integrity = db.execute("PRAGMA quick_check").fetchone()[0]
            foreign_keys = len(db.execute("PRAGMA foreign_key_check").fetchall())
        finally:
            db.close()
        after = self._sha256()
        if before != after:
            raise AMSOnboardingPreviewError("database changed during read-only preview")

        return {
            "mode": "zero-write",
            "database": str(self.database.resolve()),
            "schema": 19,
            "latest_migration": self.REQUIRED_SCHEMA,
            "sha256_before": before,
            "sha256_after": after,
            "database_unchanged": True,
            "integrity": integrity,
            "foreign_key_violations": foreign_keys,
            "parent": parent,
            "before_counts": counts,
            "units": units,
            "protected_fingerprints": protected,
            "expected_row_changes": self._expected_row_changes(units),
            "confirmation_questions": [
                (
                    "Verify AMS 1 physical label exactly reads "
                    f"{serials[0]!r}, including every dash and character."
                ),
                (
                    "Verify AMS 2 physical label exactly reads "
                    f"{serials[1]!r}, especially the space before EWR."
                ),
                "Confirm which physical unit is the existing legacy AMS 1 and which is AMS 2.",
                f"Approve the exact display names {names[0]!r} and {names[1]!r}.",
                "Confirm both units are currently physically attached to the P1S.",
                "Provide or approve the effective attachment time for immutable relationship history.",
                "Confirm model text is exactly 'AMS 2 Pro'.",
                (
                    "Confirm operational status should remain Unknown and that no "
                    "maintenance readiness or restriction is being asserted."
                ),
            ],
            "design_notes": {
                "slots": (
                    "All eight equipment_slots rows already exist and remain authoritative. "
                    "They are adopted through one-to-one legacy-container links, not recreated."
                ),
                "filament": (
                    "Existing ams_assignments continue to reference the same slot IDs. "
                    "No assignment, spool, quantity, transaction, or audit history is rewritten."
                ),
                "readiness": (
                    "Operational status is stored as unknown. No maintenance bridge is created, "
                    "so readiness remains null and the derived restriction remains unknown."
                ),
                "provenance": (
                    "No purchase or receiving link is proposed. Any later provenance remains inert."
                ),
            },
        }

    def _unit_preview(
        self,
        *,
        db,
        legacy,
        equipment_number,
        display_name,
        serial,
        parent,
        manufacturer,
        equipment_type,
        subtype,
    ):
        slots = [
            dict(row)
            for row in db.execute(
                """
                SELECT es.id slot_id,es.slot_number,es.location_id,l.name location_name,
                       aa.id assignment_id,aa.instance_id,aa.loaded_at,
                       ii.permanent_id spool_number,ii.state spool_state,
                       ii.remaining_quantity,m.name manufacturer,
                       ci.product_line,ci.variant color
                FROM equipment_slots es
                JOIN locations l ON l.id=es.location_id
                LEFT JOIN ams_assignments aa
                  ON aa.slot_id=es.id AND aa.unloaded_at IS NULL
                LEFT JOIN inventory_instances ii ON ii.id=aa.instance_id
                LEFT JOIN catalog_items ci ON ci.id=ii.catalog_item_id
                LEFT JOIN manufacturers m ON m.id=ci.manufacturer_id
                WHERE es.equipment_id=? ORDER BY es.slot_number
                """,
                (legacy["id"],),
            )
        ]
        return {
            "registry_record": {
                "id": "<allocated at commit>",
                "equipment_uuid": self.GENERATED_UUID,
                "equipment_number": equipment_number,
                "display_name": display_name,
                "equipment_type_id": equipment_type["id"],
                "equipment_type": equipment_type["type_code"],
                "equipment_subtype_id": subtype["id"],
                "equipment_subtype": subtype["subtype_code"],
                "manufacturer_id": manufacturer["id"],
                "manufacturer": manufacturer["name"],
                "model": "AMS 2 Pro",
                "manufacturer_serial_number": serial,
                "ths_asset_identifier": None,
                "current_location_id": None,
                "lifecycle_state": "installed",
                "operational_status": "unknown",
                "installed_at": None,
                "commissioned_at": None,
                "retired_at": None,
                "disposed_at": None,
                "notes": (
                    f"Linked to legacy {legacy['name']} container; existing slot "
                    "and filament assignment history preserved."
                ),
                "state_version": 1,
                "created_by": "Cowboy",
                "created_at": self.SYSTEM_COMMIT_TIME,
                "updated_at": self.SYSTEM_COMMIT_TIME,
            },
            "relationship": {
                "child_equipment_id": "<allocated registry row ID>",
                "parent_equipment_id": parent["id"],
                "parent_equipment_number": parent["equipment_number"],
                "relationship_type": "attached_to",
                "state_version": 1,
                "effective_at": self.UNCONFIRMED_EFFECTIVE_AT,
                "updated_at": self.SYSTEM_COMMIT_TIME,
            },
            "legacy_container_link": {
                "equipment_id": "<allocated registry row ID>",
                "legacy_equipment_id": legacy["id"],
                "legacy_name": legacy["name"],
                "linked_by": "Cowboy",
                "linked_at": self.SYSTEM_COMMIT_TIME,
            },
            "existing_slots_unchanged": slots,
            "expected_audit": [
                "register_equipment",
                "attach_equipment_relationship",
                "link_legacy_equipment_container",
            ],
            "expected_immutable_history": [
                "equipment_history.register",
                "equipment_relationship_history.attach",
            ],
        }

    def _validate_database(self, db):
        latest = db.execute(
            "SELECT name FROM schema_migrations ORDER BY applied_at DESC,name DESC LIMIT 1"
        ).fetchone()
        count = db.execute("SELECT COUNT(*) FROM schema_migrations").fetchone()[0]
        if count != 19 or not latest or latest[0] != self.REQUIRED_SCHEMA:
            raise AMSOnboardingPreviewError("production schema is not exactly 19")
        if db.execute("PRAGMA quick_check").fetchone()[0] != "ok":
            raise AMSOnboardingPreviewError("database integrity check failed")
        if db.execute("PRAGMA foreign_key_check").fetchone():
            raise AMSOnboardingPreviewError("database has foreign-key violations")

    def _parent(self, db):
        rows = db.execute(
            """
            SELECT er.id,er.equipment_uuid,er.equipment_number,er.display_name,
                   er.model,er.lifecycle_state,er.operational_status,er.state_version
            FROM equipment_registry er
            JOIN equipment_types et ON et.id=er.equipment_type_id
            LEFT JOIN manufacturers m ON m.id=er.manufacturer_id
            WHERE er.equipment_number=? AND et.type_code='printer'
              AND m.name='Bambu Lab' AND er.model='P1S'
            """,
            (self.PARENT_NUMBER,),
        ).fetchall()
        if len(rows) != 1:
            raise AMSOnboardingPreviewError("exact P1S parent equipment record was not found")
        return dict(rows[0])

    @staticmethod
    def _manufacturer(db):
        rows = db.execute(
            "SELECT id,name FROM manufacturers WHERE name='Bambu Lab' AND archived_at IS NULL"
        ).fetchall()
        if len(rows) != 1:
            raise AMSOnboardingPreviewError("exact Bambu Lab manufacturer is unavailable")
        return dict(rows[0])

    @staticmethod
    def _type_rows(db):
        equipment_type = db.execute(
            "SELECT * FROM equipment_types WHERE type_code='ams_unit' AND active=1"
        ).fetchone()
        subtype = db.execute(
            """
            SELECT es.* FROM equipment_subtypes es
            JOIN equipment_types et ON et.id=es.equipment_type_id
            WHERE et.type_code='ams_unit' AND es.subtype_code='bambu_ams' AND es.active=1
            """
        ).fetchone()
        if not equipment_type or not subtype:
            raise AMSOnboardingPreviewError("AMS equipment type configuration is unavailable")
        return dict(equipment_type), dict(subtype)

    def _legacy_units(self, db):
        rows = [
            dict(row)
            for row in db.execute(
                """
                SELECT e.* FROM equipment e
                WHERE e.equipment_type='AMS' AND e.archived_at IS NULL
                ORDER BY e.name,e.id
                """
            )
        ]
        if [row["name"] for row in rows] != ["AMS 1", "AMS 2"]:
            raise AMSOnboardingPreviewError("legacy AMS containers are not exactly AMS 1 and AMS 2")
        for row in rows:
            slots = [
                item[0]
                for item in db.execute(
                    "SELECT slot_number FROM equipment_slots WHERE equipment_id=? ORDER BY slot_number",
                    (row["id"],),
                )
            ]
            if row["slot_count"] != 4 or slots != [1, 2, 3, 4]:
                raise AMSOnboardingPreviewError(
                    f"{row['name']} does not have exactly unique slots 1 through 4"
                )
            if db.execute(
                "SELECT 1 FROM equipment_legacy_container_links WHERE legacy_equipment_id=?",
                (row["id"],),
            ).fetchone():
                raise AMSOnboardingPreviewError(
                    f"{row['name']} is already linked to Equipment Registry"
                )
        return rows

    def _reject_duplicates(self, db, serials, names):
        existing_serials = {
            self._normalized(row[0])
            for row in db.execute(
                """
                SELECT manufacturer_serial_number FROM equipment_registry
                WHERE manufacturer_serial_number IS NOT NULL
                """
            )
        }
        if any(self._normalized(value) in existing_serials for value in serials):
            raise AMSOnboardingPreviewError("reported manufacturer serial is already registered")
        existing_names = {
            self._normalized(row[0])
            for row in db.execute("SELECT display_name FROM equipment_registry")
        }
        if any(self._normalized(value) in existing_names for value in names):
            raise AMSOnboardingPreviewError("proposed AMS display name is already registered")

    @staticmethod
    def _next_numbers(db, count):
        maximum = 0
        for row in db.execute("SELECT equipment_number FROM equipment_registry"):
            try:
                maximum = max(maximum, int(row[0].removeprefix("THS-EQP-")))
            except ValueError as exc:
                raise AMSOnboardingPreviewError(
                    "existing equipment number sequence is invalid"
                ) from exc
        return [f"THS-EQP-{maximum + offset:06d}" for offset in range(1, count + 1)]

    @staticmethod
    def _counts(db):
        return dict(
            db.execute(
                """
                SELECT
                  (SELECT COUNT(*) FROM equipment_registry) equipment_registry,
                  (SELECT COUNT(*) FROM equipment_history) equipment_history,
                  (SELECT COUNT(*) FROM equipment_relationship_state) relationship_state,
                  (SELECT COUNT(*) FROM equipment_relationship_history) relationship_history,
                  (SELECT COUNT(*) FROM equipment_legacy_container_links) legacy_links,
                  (SELECT COUNT(*) FROM equipment_slots) equipment_slots,
                  (SELECT COUNT(*) FROM ams_assignments) all_assignments,
                  (SELECT COUNT(*) FROM ams_assignments WHERE unloaded_at IS NULL) active_assignments,
                  (SELECT COUNT(*) FROM audit_events WHERE module='equipment-registry') registry_audits
                """
            ).fetchone()
        )

    @staticmethod
    def _protected_fingerprints(db):
        result = {}
        for table in (
            "equipment",
            "equipment_slots",
            "ams_assignments",
            "inventory_instances",
            "inventory_transactions",
            "transaction_lines",
        ):
            rows = db.execute(f"SELECT * FROM {table} ORDER BY rowid").fetchall()
            encoded = repr([tuple(row) for row in rows]).encode()
            result[table] = hashlib.sha256(encoded).hexdigest().upper()
        return result

    @staticmethod
    def _expected_row_changes(units):
        rows = []
        for unit in units:
            number = unit["registry_record"]["equipment_number"]
            rows.extend(
                [
                    {"table": "equipment_registry", "operation": "INSERT", "equipment": number},
                    {"table": "equipment_history", "operation": "INSERT", "equipment": number},
                    {"table": "audit_events", "operation": "INSERT", "equipment": number,
                     "event_type": "register_equipment"},
                    {"table": "equipment_relationship_state", "operation": "INSERT",
                     "equipment": number},
                    {"table": "equipment_relationship_history", "operation": "INSERT",
                     "equipment": number, "action_type": "attach"},
                    {"table": "audit_events", "operation": "INSERT", "equipment": number,
                     "event_type": "attach_equipment_relationship"},
                    {"table": "equipment_legacy_container_links", "operation": "INSERT",
                     "equipment": number},
                    {"table": "audit_events", "operation": "INSERT", "equipment": number,
                     "event_type": "link_legacy_equipment_container"},
                ]
            )
        return {
            "inserts": rows,
            "updates": [],
            "deletes": [],
            "slot_rows_created": 0,
            "slot_rows_changed": 0,
            "assignment_rows_changed": 0,
            "total_insert_rows": len(rows),
        }

    def _sha256(self):
        return hashlib.sha256(self.database.read_bytes()).hexdigest().upper()

    @staticmethod
    def _reported_serial(value, label):
        if not isinstance(value, str) or not value:
            raise AMSOnboardingPreviewError(f"{label} reported serial is required")
        if value != value.strip():
            raise AMSOnboardingPreviewError(
                f"{label} reported serial has unverified leading or trailing whitespace"
            )
        if any(ord(character) < 32 for character in value):
            raise AMSOnboardingPreviewError(f"{label} reported serial contains control characters")
        return value

    @staticmethod
    def _exact_name(value, label):
        if not isinstance(value, str) or not value or value != value.strip():
            raise AMSOnboardingPreviewError(f"{label} proposed display name is invalid")
        return value

    @staticmethod
    def _normalized(value):
        return " ".join(value.casefold().split())
