"use strict";
(function(){
  const UNDOCUMENTED="RESPONSIBILITIES NOT YET DOCUMENTED IN THIS MILESTONE";const CREW=Object.freeze([{code:"M2",id:"maeve",name:"MAEVE",role:"COMMANDER",responsibilities:UNDOCUMENTED,portrait:"./assets/crew/maeve_crew_portrait_photoreal_v2.png"},{code:"AD",id:"addie",name:"ADDIE",role:"QUARTERMASTER",responsibilities:UNDOCUMENTED,portrait:"./assets/crew/addie_quartermaster_portrait_photoreal_v2.png"},{code:"MD",id:"maddie",name:"MADDIE",role:"DOC",responsibilities:UNDOCUMENTED,portrait:"./assets/crew/maddie_doc_portrait_photoreal_v2.png"},{code:"CL",id:"callie",name:"CALLIE",role:"RELAY",responsibilities:UNDOCUMENTED,portrait:"./assets/crew/callie_relay_portrait_v1.png"},{code:"IS",id:"isla",name:"ISLA",role:"SCOUT",responsibilities:UNDOCUMENTED,portrait:"./assets/crew/isla_scout_portrait_photoreal_v2.png"},{code:"JB",id:"junior-bub",name:"JUNIOR / BUB",role:"HAMMER",responsibilities:UNDOCUMENTED,portrait:"./assets/crew/junior_bub_hammer_portrait_v1.png"},{code:"OL",id:"oliver",name:"OLIVER",role:"FORGE",responsibilities:UNDOCUMENTED,portrait:"./assets/crew/oliver_forge_portrait_photoreal_v2.png"},{code:"AI",id:"aiden",name:"AIDEN",role:"BROKER",responsibilities:UNDOCUMENTED,portrait:"./assets/crew/aiden_broker_portrait_v1.png"},{code:"SO",id:"shop-ops",name:"SHOP OPS",role:"PRINT-SHOP MECHANIC",responsibilities:"PRINTERS · FILAMENT · INVENTORY · MAINTENANCE INTERPRETATION",portrait:"./assets/crew/shop_ops_female_portrait_v1.png"}]);
  const STAGES=Object.freeze(["broker","stt","voice","voice-ready","maeve-ready"]),tabs=[...document.querySelectorAll("[data-view]")],panels=[...document.querySelectorAll("[data-view-panel]")],viewLabel=document.getElementById("active-view-label");
  function openView(name){if(!panels.some(panel=>panel.dataset.viewPanel===name))return false;for(const tab of tabs){const active=tab.dataset.view===name;tab.classList.toggle("is-active",active);if(active)tab.setAttribute("aria-current","page");else tab.removeAttribute("aria-current");}for(const panel of panels){const active=panel.dataset.viewPanel===name;panel.hidden=!active;panel.classList.toggle("is-active",active);}viewLabel.textContent=name.toUpperCase();return true;}
  for(const tab of tabs)tab.addEventListener("click",()=>openView(tab.dataset.view));for(const button of document.querySelectorAll("[data-open-view]"))button.addEventListener("click",()=>openView(button.dataset.openView));
  const portraitMarkup=member=>member.portrait?`<img class="crew-portrait" src="${member.portrait}" alt="Approved portrait of ${member.name}">`:`<span class="portrait-pending" role="img" aria-label="Portrait pending for ${member.name}">PORTRAIT PENDING</span>`;const roster=document.getElementById("home-roster"),crewDetail=document.getElementById("crew-detail"),detailName=document.getElementById("crew-detail-name"),detailRole=document.getElementById("crew-detail-role"),detailResponsibilities=document.getElementById("crew-detail-responsibilities"),detailPortrait=document.getElementById("crew-detail-portrait");roster.innerHTML=CREW.map(member=>`<button class="roster-row" type="button" data-crew-id="${member.id}" aria-label="Open ${member.name}, ${member.role} details">${portraitMarkup(member)}<span class="roster-copy"><strong>${member.name}</strong><small>${member.role}</small><em>IDLE / AVAILABLE</em><em>NO ASSIGNED TASK</em></span></button>`).join("");
  function openCrewDetail(id){const member=CREW.find(item=>item.id===id);if(!member)return false;detailName.textContent=member.name;detailRole.textContent=member.role;detailResponsibilities.textContent=member.responsibilities;detailPortrait.innerHTML=portraitMarkup(member);roster.hidden=true;crewDetail.hidden=false;document.getElementById("crew-detail-close").focus();return true;}function closeCrewDetail(){crewDetail.hidden=true;roster.hidden=false;roster.querySelector("button").focus();}for(const entry of roster.querySelectorAll("[data-crew-id]"))entry.addEventListener("click",()=>openCrewDetail(entry.dataset.crewId));document.getElementById("crew-detail-close").addEventListener("click",closeCrewDetail);
  const maeveStage=document.getElementById("maeve-command-stage"),focusReturn=document.getElementById("focus-return");function openConversationMode(){document.body.classList.add("conversation-focus");maeveStage.setAttribute("aria-expanded","true");focusReturn.focus();}function closeConversationMode(){document.body.classList.remove("conversation-focus");maeveStage.setAttribute("aria-expanded","false");maeveStage.focus();}maeveStage.addEventListener("click",event=>{if(event.target.closest("button"))return;openConversationMode();});maeveStage.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openConversationMode();}});focusReturn.addEventListener("click",event=>{event.stopPropagation();closeConversationMode();});
  const cleanView=document.getElementById("clean-view"),restoreCommandView=document.getElementById("restore-command-view"),restoreStatus=document.getElementById("restore-status"),restoreVoice=document.getElementById("restore-voice");function syncCleanControls(){const clean=document.body.classList.contains("clean-view"),left=document.body.classList.contains("show-status"),right=document.body.classList.contains("show-voice");cleanView.hidden=clean;restoreCommandView.hidden=!clean;restoreStatus.hidden=!clean||left;restoreVoice.hidden=!clean||right;}function setCleanView(enabled){document.body.classList.toggle("clean-view",enabled);document.body.classList.remove("show-status","show-voice");syncCleanControls();}cleanView.addEventListener("click",()=>setCleanView(true));restoreCommandView.addEventListener("click",()=>setCleanView(false));restoreStatus.addEventListener("click",()=>{document.body.classList.add("show-status");syncCleanControls();});restoreVoice.addEventListener("click",()=>{document.body.classList.add("show-voice");syncCleanControls();});
  const mobileStatus=document.getElementById("mobile-status"),mobileVoice=document.getElementById("mobile-voice");function selectMobilePanel(name){const voice=name==="voice";document.body.classList.toggle("mobile-voice-selected",voice);mobileStatus.classList.toggle("is-active",!voice);mobileVoice.classList.toggle("is-active",voice);mobileStatus.setAttribute("aria-pressed",String(!voice));mobileVoice.setAttribute("aria-pressed",String(voice));(voice?document.querySelector(".voice-command-column"):document.querySelector(".printer-card"))?.scrollIntoView({block:"start",behavior:globalThis.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});}mobileStatus.addEventListener("click",()=>selectMobilePanel("status"));mobileVoice.addEventListener("click",()=>selectMobilePanel("voice"));
  const failure=document.getElementById("startup-failure"),details=document.getElementById("startup-details"),failureMessage=document.getElementById("startup-failure-message"),textOnly=document.getElementById("start-text-only"),summary=document.getElementById("startup-summary");let failedStage=null;
  function resetStages(){for(const item of document.querySelectorAll("[data-stage]")){item.classList.remove("is-active","is-passed","is-failed");item.querySelector("strong").textContent="WAITING";}failure.hidden=true;details.hidden=true;textOnly.hidden=true;failedStage=null;summary.textContent="CHECKING";}
  function stageStarted(name){const index=STAGES.indexOf(name);if(index<0)throw new Error("Unknown startup stage");for(let i=0;i<index;i++){if(!document.querySelector(`[data-stage="${STAGES[i]}"]`).classList.contains("is-passed"))throw new Error("Startup stage order violation");}const item=document.querySelector(`[data-stage="${name}"]`);item.classList.add("is-active");item.querySelector("strong").textContent="CHECKING";}
  function stagePassed(name){const item=document.querySelector(`[data-stage="${name}"]`);if(!item.classList.contains("is-active"))throw new Error("Startup stage was not checked");item.classList.remove("is-active");item.classList.add("is-passed");item.querySelector("strong").textContent="VERIFIED";if(name==="maeve-ready")summary.textContent="MAEVE READY";}
  function stageFailed(name,message,sanitizedDetail,voiceOnly=false){const item=document.querySelector(`[data-stage="${name}"]`);item.classList.remove("is-active");item.classList.add("is-failed");item.querySelector("strong").textContent="FAILED";failedStage=name;summary.textContent="FAILED";failureMessage.textContent=message;details.textContent=sanitizedDetail;failure.hidden=false;textOnly.hidden=!voiceOnly;}
  document.getElementById("show-startup-details").addEventListener("click",()=>{details.hidden=!details.hidden;});document.getElementById("retry-failed-stage").addEventListener("click",()=>{if(!failedStage)return;const stage=failedStage,item=document.querySelector(`[data-stage="${stage}"]`);item.classList.remove("is-failed");item.classList.add("is-active");item.querySelector("strong").textContent="CHECKING";failure.hidden=true;summary.textContent="CHECKING";document.dispatchEvent(new CustomEvent("maeve:retry-stage",{detail:{stage}}));});document.getElementById("close-maeve").addEventListener("click",()=>document.dispatchEvent(new CustomEvent("maeve:close-requested")));document.getElementById("start-text-only").addEventListener("click",()=>document.dispatchEvent(new CustomEvent("maeve:text-only-requested",{detail:{explicit:true}})));
  function applySyntheticScenario(name){if(!["success","broker-failure","voice-failure","muted","ended"].includes(name))return false;resetStages();if(name==="broker-failure"){stageStarted("broker");stageFailed("broker","Maeve could not start the local broker.","SYNTHETIC_BROKER_FAILURE");return true;}for(const stage of ["broker","stt","voice"]){stageStarted(stage);if(name==="voice-failure"&&stage==="voice"){stageFailed("voice","Maeve voice is unavailable.","SYNTHETIC_VOICE_PROVIDER_FAILURE",true);return true;}stagePassed(stage);}for(const stage of ["voice-ready","maeve-ready"]){stageStarted(stage);stagePassed(stage);}const state=document.getElementById("runtime-state"),detail=document.getElementById("runtime-detail"),session=document.getElementById("conversation-session");if(name==="muted"){state.textContent="MUTED";detail.textContent="— MICROPHONE CLOSED · DELIBERATE UNMUTE REQUIRED";session.dataset.state="MUTED";document.body.dataset.voiceState="MUTED";}else if(name==="ended"){state.textContent="OFF";detail.textContent="— CONTEXT CLEARED · MICROPHONE CLOSED · MODE ENDED";session.dataset.state="OFF";document.body.dataset.voiceState="ENDED";}else{state.textContent="READY";detail.textContent="— VERIFIED SYNTHETIC STARTUP · NO OPERATIONAL CALLS";session.dataset.state="READY";document.body.dataset.voiceState="READY";}return true;}
  const query=new URLSearchParams(location.search),synthetic=query.get("synthetic"),requestedView=query.get("view");if(synthetic)applySyntheticScenario(synthetic);if(requestedView)openView(requestedView);if(query.get("focus")==="conversation")openConversationMode();
  globalThis.MAEVE_HALO_ANALYZER?.applyValues({});
  globalThis.MAEVE_INTEGRATED_UI=Object.freeze({crew:CREW,stages:STAGES,openView,openCrewDetail,closeCrewDetail,openConversationMode,closeConversationMode,setCleanView,selectMobilePanel,resetStages,stageStarted,stagePassed,stageFailed,applySyntheticScenario});
})();
