"use strict";
const RUNTIME_VERSION="0.5.0-stage13";
const APPROVED_TEXT="Good morning, operator. Maeve’s live voice and visual systems are operating together for the first time.";
const HOME_ROSTER=Object.freeze([["M2","MAEVE","COMMAND","LOCAL / READY"],["FG","FORGE","ENGINEERING","AVAILABLE"],["SC","SCOUT","INTELLIGENCE","AVAILABLE"],["OP","OPS","OPERATIONS","AVAILABLE"],["DC","DOC","CARE","AVAILABLE"],["SO","SHOP OPS","FABRICATION","AVAILABLE"],["QM","QUARTERMASTER","LOGISTICS","AVAILABLE"]].map(Object.freeze));
const runtimeState=document.getElementById("runtime-state"),runtimeDetail=document.getElementById("runtime-detail"),runtimeDot=document.getElementById("runtime-dot"),haloState=document.getElementById("halo-state"),voiceState=document.getElementById("voice-state"),voiceText=document.getElementById("voice-text"),speakButton=document.getElementById("voice-speak"),stopButton=document.getElementById("voice-stop"),reviewCancelButton=document.getElementById("ptt-cancel-response"),reviewResponse=document.getElementById("ptt-response"),providerIndicator=document.getElementById("voice-provider-indicator");
const tokenParameters=new URLSearchParams(location.hash.startsWith("#")?location.hash.slice(1):location.hash);
const runtimeToken=tokenParameters.get("token")||"";
const launchAuthorized=/^[a-f0-9]{64}$/i.test(runtimeToken);
if(location.hash)history.replaceState(null,"",`${location.pathname}${location.search}`);
let activePlayback=null,generationConsumed=false,brokerReady=false,playbackOnly=false,playbackFacts=null,pttBusy=false,pttController=null,conversationController=null,responseCleanupSent=false,approvedDeviceId=null,activeReviewResponse=null,selectedVoiceProvider=null,runtimeConfiguration=null;
const stateSequence=[];
const analyzerMetrics={samples:0,lowMin:1,lowMax:0,midMin:1,midMax:0,highMin:1,highMax:0,scaleMin:2,scaleMax:0,opacityMin:2,opacityMax:0};
document.getElementById("home-roster").innerHTML=HOME_ROSTER.map(member=>`<div class="roster-row" aria-label="${member[1]} informational roster fixture"><span class="roster-code">${member[0]}</span><span><strong>${member[1]}</strong><small>${member[2]}</small><em>${member[3]}</em></span></div>`).join("");
voiceText.value="";
function setState(state,detail){stateSequence.push({state,at:new Date().toISOString()});runtimeState.textContent=state;runtimeDetail.textContent=`— ${detail}`;voiceState.textContent=state;runtimeDot.className=`state-dot state-${state.toLowerCase()}`;}
function setPttState(state,detail){document.getElementById("ptt-state").textContent=state;setState(state,detail);}
function voiceProviderLabel(){if(selectedVoiceProvider==="ELEVENLABS")return "ELEVENLABS · MAEVE DUBLIN COMMAND · SPEED 0.90";if(selectedVoiceProvider==="QWEN")return "LOCAL QWEN · CANDIDATE B";throw new Error("EXPLICIT VOICE PROVIDER REQUIRED");}
function apiFetch(path,options={}){const headers=new Headers(options.headers||{});headers.set("X-Maeve-Token",runtimeToken);return fetch(path,{...options,headers,cache:"no-store",credentials:"omit"});}
function setPttBusy(value){pttBusy=value;if(value){speakButton.disabled=true;stopButton.disabled=true;}else{speakButton.disabled=!brokerReady||!playbackOnly||Boolean(activePlayback);stopButton.disabled=!activePlayback;}}
function publishReviewResponse(responseId,text){if(!/^[a-f0-9]{32}$/.test(responseId)||typeof text!=="string"||text.length===0||text.length>360)throw new Error("INVALID REVIEW RESPONSE DISPLAY CONTRACT");if(activeReviewResponse?.responseId===responseId){if(activeReviewResponse.text!==text)throw new Error("REVIEW RESPONSE IDENTITY MISMATCH");return false;}activeReviewResponse=Object.freeze({responseId,text});reviewResponse.textContent=text;return true;}
function updateMotionState(){const reduced=globalThis.MAEVE_HALO_ANALYZER.reducedMotionActive();document.body.classList.toggle("reduced-motion-state",reduced);if(!activePlayback)haloState.textContent=reduced?"HALO: IDLE · REDUCED MOTION ACTIVE":"HALO: IDLE BREATHING · NO AUDIO INPUT";}
function updateAnalyzer(values){analyzerMetrics.samples+=1;for(const key of ["low","mid","high","scale","opacity"]){analyzerMetrics[`${key}Min`]=Math.min(analyzerMetrics[`${key}Min`],values[key]);analyzerMetrics[`${key}Max`]=Math.max(analyzerMetrics[`${key}Max`],values[key]);}}
async function submitEvidence(playback){try{await apiFetch("/api/session-evidence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({runtimeVersion:RUNTIME_VERSION,stateSequence,playback,analyzer:analyzerMetrics})});}catch(_error){}}
async function closeLocalPlayback(playback){if(!playback)return;playback.analyzer.stop();try{await playback.audioContext.close();}catch(_error){}globalThis.MAEVE_HALO_ANALYZER.applyValues({});reviewCancelButton.disabled=true;reviewCancelButton.hidden=true;stopButton.disabled=true;speakButton.disabled=!playbackOnly||pttBusy;}
async function finishPlayback(result,error=null){const playback=activePlayback;if(!playback)return;activePlayback=null;await closeLocalPlayback(playback);try{if(playback.kind==="stage13-response"){const completed=await apiFetch("/api/response/playback-complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({result:error?"FAILED":"COMPLETED",runtimeVersion:RUNTIME_VERSION,responseId:playback.responseId})});if(!completed.ok)throw new Error("RESPONSE CLEANUP GATE FAILED");responseCleanupSent=true;}if(error)throw new Error(error);setState("READY",playback.kind==="stage13-response"?"CONTROLLED RESPONSE COMPLETE · QWEN STOPPED":playback.kind==="conversation-response"?"CONVERSATION AUDIO COMPLETE · BROKER ACKNOWLEDGMENT REQUIRED":"PLAYBACK COMPLETE · READY FOR MANUAL REPLAY");updateMotionState();await submitEvidence({result,error:null,endedAt:new Date().toISOString(),audio:playbackFacts});playback.resolve({cancelled:false});}catch(failure){const message=failure instanceof Error?failure.message:"PLAYBACK FAILURE";setState("FAILED",message);haloState.textContent="HALO: ANALYZER ERROR · IDLE VISUAL ONLY";await submitEvidence({result:"FAILED",error:message,endedAt:new Date().toISOString(),audio:playbackFacts});playback.reject(failure);}}
async function playValidatedAudio(audioUrl,audioContract,kind="stage9-review",responseId=null){if(activePlayback)throw new Error("LOCAL AUDIO ALREADY ACTIVE");if(pttBusy&&!['stage13-response','conversation-response'].includes(kind))throw new Error("PTT OWNS LOCAL AUDIO MODE");if(["stage13-response","conversation-response"].includes(kind)&&!/^[a-f0-9]{32}$/.test(responseId||""))throw new Error("INVALID RESPONSE IDENTITY");if(!audioContract||audioContract.sampleRate!==24000||audioContract.channels!==1||audioContract.bytes<=0)throw new Error("INVALID WAV CONTRACT");const AudioContextClass=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioContextClass)throw new Error("ANALYZER ERROR");const audioHeaders=responseId?{"X-Maeve-Response-Id":responseId}:{};const response=await apiFetch(audioUrl,{headers:audioHeaders});if(!response.ok)throw new Error("PLAYBACK AUDIO UNAVAILABLE");const bytes=await response.arrayBuffer();if(bytes.byteLength!==audioContract.bytes)throw new Error("WAV BYTE CONTRACT MISMATCH");const audioContext=new AudioContextClass();await audioContext.resume();const buffer=await audioContext.decodeAudioData(bytes.slice(0));if(buffer.numberOfChannels!==1||buffer.duration<=0)throw new Error("INVALID DECODED AUDIO");playbackFacts={nativeSampleRate:audioContract.sampleRate,decodedPlaybackSampleRate:buffer.sampleRate,channels:buffer.numberOfChannels,durationSeconds:buffer.duration,bytes:bytes.byteLength};const source=audioContext.createBufferSource();source.buffer=buffer;const analyzer=globalThis.MAEVE_HALO_ANALYZER.create(audioContext,source,{destinationNode:audioContext.destination,onSample:updateAnalyzer});let playback;const completion=new Promise((resolve,reject)=>{playback={audioContext,source,analyzer,kind,responseId,resolve,reject};activePlayback=playback;});stopButton.disabled=["stage13-response","conversation-response"].includes(kind);reviewCancelButton.hidden=kind!=="stage13-response";reviewCancelButton.disabled=kind!=="stage13-response";setState("SPEAKING",`${voiceProviderLabel()} PLAYBACK ACTIVE · MICROPHONE CLOSED`);haloState.textContent="HALO: REAL AUDIO ANALYZER ACTIVE";analyzer.start();source.addEventListener("ended",()=>{if(activePlayback===playback)finishPlayback("COMPLETED");},{once:true});source.start();return completion;}
async function cancelReviewPlayback(){const playback=activePlayback;if(!playback||playback.kind!=="stage13-response"){pttController?.ensureMicrophoneClosed();return {cancelled:false};}activePlayback=null;try{try{playback.source.stop();}catch(_error){}await closeLocalPlayback(playback);const closed=pttController?.ensureMicrophoneClosed();if(closed&&!closed.ended)throw new Error("MICROPHONE CLOSURE FAILED DURING CANCEL");const response=await apiFetch("/api/response/cancel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"cancel-review-response",runtimeVersion:RUNTIME_VERSION,responseId:playback.responseId})});const result=await response.json();if(!response.ok||!["CANCELLED","ALREADY_CANCELLED"].includes(result.status)||result.microphone!=="PTT_ONLY_CLOSED")throw new Error(result.error||"REVIEW RESPONSE CANCELLATION FAILED");responseCleanupSent=true;setPttState("READY","RESPONSE CANCELLED · QWEN STOPPED · MICROPHONE CLOSED");updateMotionState();playback.resolve({cancelled:true});return {cancelled:true};}catch(error){playback.reject(error);throw error;}}
async function approveAndRespond(transcriptId,approvedText){if(!brokerReady||activePlayback)throw new Error("CONTROLLED RESPONSE START GATE FAILED");responseCleanupSent=false;let responseId=null;try{setState("THINKING","EDITED APPROVAL CONSUMED · RESTRICTED OPENAI TEXT REASONING");const response=await apiFetch("/api/response/approve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"approve-edited-transcript-and-respond",runtimeVersion:RUNTIME_VERSION,transcriptId,approvedText})});const result=await response.json();if(!response.ok||result.status!=="READY_FOR_PLAYBACK"||typeof result.text!=="string"||result.text.length===0||result.text.length>360||!result.audioUrl||!/^[a-f0-9]{32}$/.test(result.responseId||"")||!result.reviewAudit)throw new Error(result.error||"CONTROLLED RESPONSE GENERATION FAILED");responseId=result.responseId;publishReviewResponse(responseId,result.text);return await playValidatedAudio(result.audioUrl,result.audio,"stage13-response",responseId);}catch(error){if(responseId&&!responseCleanupSent){try{const cleanup=await apiFetch("/api/response/cancel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"cancel-review-response",runtimeVersion:RUNTIME_VERSION,responseId})});responseCleanupSent=cleanup.ok;}catch(_cleanupError){}}throw error;}}
async function discardTranscript(transcriptId){const response=await apiFetch("/api/response/discard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"discard-local-transcript",runtimeVersion:RUNTIME_VERSION,transcriptId})});if(!response.ok)throw new Error("LOCAL TRANSCRIPT DISCARD FAILED");return response.json();}
async function speak(){if(!brokerReady||pttBusy)return;speakButton.disabled=true;voiceText.readOnly=true;if(playbackOnly){try{await playValidatedAudio("/api/audio/stage9.wav",{sampleRate:24000,channels:1,bytes:284204});}catch(error){await finishPlayback("FAILED",error instanceof Error?error.message:"ERROR");}return;}if(generationConsumed||voiceText.value!==APPROVED_TEXT)return;generationConsumed=true;setState("GENERATING","CANONICAL LOCAL QWEN · ONE ATTEMPT");try{const response=await apiFetch("/api/speak",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:APPROVED_TEXT,runtimeVersion:RUNTIME_VERSION})});if(!response.ok)throw new Error("GENERATION FAILED · NO RETRY");const result=await response.json();if(result.status!=="READY_FOR_PLAYBACK"||!result.audioUrl)throw new Error("INVALID AUDIO RESPONSE");await playValidatedAudio(result.audioUrl,result.audio);}catch(error){await finishPlayback("FAILED",error instanceof Error?error.message:"ERROR");}}
function stopPlayback(){if(!activePlayback)return;try{activePlayback.source.stop();}catch(_error){}}
async function cancelConversationPlayback(){const playback=activePlayback;if(!playback||playback.kind!=="conversation-response")return {cancelled:false};activePlayback=null;try{try{playback.source.stop();}catch(_error){}await closeLocalPlayback(playback);updateMotionState();playback.resolve({cancelled:true});return {cancelled:true};}catch(error){playback.reject(error);throw error;}}
function initializeControllers(){if(pttController||conversationController||!runtimeConfiguration)throw new Error("Runtime controller configuration replay rejected");const microphone=runtimeConfiguration.microphone;if(!microphone||typeof microphone.approvedLabel!=="string"||typeof microphone.approvedSelector!=="string")throw new Error("Approved microphone configuration rejected");conversationController=globalThis.MAEVE_CONVERSATION_CONTROLLER.create({runtimeVersion:RUNTIME_VERSION,apiFetch,setState:setPttState,deviceId:()=>approvedDeviceId,approvedLabel:microphone.approvedLabel,voiceProviderLabel,playbackActive:()=>Boolean(activePlayback),playResponse:data=>playValidatedAudio(data.audioUrl,data.audio,"conversation-response",data.responseId),cancelConversationPlayback});pttController=globalThis.MAEVE_PTT_CONTROLLER.create({authorized:launchAuthorized,apiFetch,setState:setPttState,setBusy:setPttBusy,playbackActive:()=>Boolean(activePlayback),approvedLabel:microphone.approvedLabel,approvedSelector:microphone.approvedSelector,approveAndRespond,discardTranscript,onEndpointVerified:id=>{approvedDeviceId=id;conversationController.endpointReady();}});}
async function checkBroker(){if(!launchAuthorized){setState("UNAVAILABLE","VALID 64-CHARACTER LAUNCH TOKEN REQUIRED");return;}setState("STARTING","VERIFYING LOCAL PIPELINE AND OPENAI GATEWAY");for(let attempt=0;attempt<120;attempt+=1){try{const response=await apiFetch("/health");if(!response.ok)throw new Error("HEALTH UNAVAILABLE");const health=await response.json();if(health.runtime!=="maeve-v2-live"||health.version!==RUNTIME_VERSION||health.microphone!=="PTT_ONLY_CLOSED"||health.networkProvider!=="OPENAI_CODEX_ONLY"||health.localModelNetwork!=="BLOCKED"||health.gpuOwner!=="NONE"||health.reasoningProvider!=="OPENAI_CODEX_SUBSCRIPTION"||health.reasoningModel!=="gpt-5.6-sol"||health.reasoningToolEvents!==0||!health.voiceProvider||!["ELEVENLABS","QWEN"].includes(health.voiceProvider.provider))throw new Error("UI/RUNTIME SECURITY CONTRACT MISMATCH");selectedVoiceProvider=health.voiceProvider.provider;providerIndicator.textContent=`▲   ${health.voiceProvider.display}`;if(!runtimeConfiguration){const configResponse=await apiFetch("/api/config");if(!configResponse.ok)throw new Error("RUNTIME CONFIGURATION UNAVAILABLE");runtimeConfiguration=await configResponse.json();initializeControllers();}if(health.voiceState==="IDLE"&&health.voiceProvider.available&&health.runMode==="CONTROLLED_CONVERSATION"){brokerReady=true;generationConsumed=true;playbackOnly=false;voiceText.value=APPROVED_TEXT;voiceText.disabled=true;speakButton.disabled=true;setState("READY",`ONLINE — OPENAI · LOCAL MIC/STT · ${health.voiceProvider.display}`);return;}if(["ERROR","UNAVAILABLE"].includes(health.voiceState)){setState(health.voiceState,health.voiceProvider.display||"VOICE UNAVAILABLE");return;}throw new Error("CONTROLLED-CONVERSATION SERVER REQUIRED");}catch(error){if(attempt===119){setState("UNAVAILABLE",error instanceof Error?error.message:"BRIDGE FAILURE");return;}}await new Promise(resolve=>setTimeout(resolve,500));}}
speakButton.addEventListener("click",speak);stopButton.addEventListener("click",stopPlayback);reviewCancelButton.addEventListener("click",()=>{cancelReviewPlayback().catch(error=>setPttState("FAILED",error instanceof Error?error.message:"REVIEW RESPONSE CANCELLATION FAILED"));});voiceText.addEventListener("input",()=>{speakButton.disabled=!brokerReady||generationConsumed||voiceText.value!==APPROVED_TEXT||pttBusy;});const motionQuery=globalThis.matchMedia("(prefers-reduced-motion: reduce)");motionQuery.addEventListener?.("change",updateMotionState);updateMotionState();
window.addEventListener("pagehide",()=>{activeReviewResponse=null;reviewResponse.textContent="";pttController?.shutdown();conversationController?.shutdown();},{once:true});
checkBroker();
