const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const sharp=require('sharp');
const root=path.resolve(__dirname,'../ui'),out=path.resolve(__dirname,'../evidence/specialist-focus-20260903');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
const expected=[['maeve','MAEVE','COMMANDER','maeve_crew_portrait_photoreal_v2.png'],['addie','ADDIE','QUARTERMASTER','addie_quartermaster_portrait_photoreal_v2.png'],['maddie','MADDIE','DOC','maddie_doc_portrait_photoreal_v2.png'],['callie','CALLIE','RELAY','callie_relay_portrait_v1.png'],['isla','ISLA','SCOUT','isla_scout_portrait_photoreal_v2.png'],['junior-bub','JUNIOR / BUB','HAMMER','junior_bub_hammer_portrait_v1.png'],['oliver','OLIVER','FORGE','oliver_forge_portrait_photoreal_v2.png'],['aiden','AIDEN','BROKER','aiden_broker_portrait_v1.png'],['shop-ops','SHOP OPS','PRINT-SHOP MECHANIC','shop_ops_female_portrait_v1.png']];
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 fs.mkdirSync(out,{recursive:true});const origin=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'reduce'});let external=0,api=0,baseline=false;const errors=[];
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==origin){external++;return route.abort();}if(u.pathname.startsWith('/api/')){api++;return route.abort();}if(baseline&&u.pathname==='/'){const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/^.*(?:styles\/specialist-focus|scripts\/specialist-focus).*\r?\n/gm,'');return route.fulfill({contentType:'text/html',body:html});}return route.continue();});
 await context.addInitScript(()=>{window.audioRequests=0;const deny=()=>{window.audioRequests++;throw Error('Audio forbidden');};navigator.mediaDevices.getUserMedia=deny;window.AudioContext=deny;window.webkitAudioContext=deny;HTMLMediaElement.prototype.play=deny;});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 async function load(url='/'){await page.goto(origin+url);await page.waitForLoadState('networkidle');await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));await page.evaluate(()=>document.fonts.ready);
  if(await page.locator('#specialist-focus').count() && await page.locator('#specialist-focus').evaluate(e=>e.open)){
   const m=await page.evaluate(()=>{const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,w:r.width,h:r.height};};const i=document.querySelector('#specialist-portrait');return{portrait:box('#specialist-portrait'),stage:box('.specialist-stage'),wave:box('.specialist-wave'),identity:box('.specialist-identity'),status:box('.specialist-status'),fit:getComputedStyle(i).objectFit,ratio:i.naturalWidth/i.naturalHeight,halo:getComputedStyle(document.querySelector('.specialist-static-halo')).pointerEvents,width:innerWidth,height:innerHeight};});
   assert.equal(m.fit,'contain');assert(m.ratio>0);assert(m.portrait.y>=m.identity.bottom);assert(m.portrait.x>=0&&m.portrait.right<=m.width);assert(m.portrait.y>=m.stage.y&&m.portrait.bottom<=m.stage.bottom);assert(m.wave.y>=m.portrait.bottom+23.5,'Portrait/wave separation');assert(m.status.y>=m.wave.bottom,'Wave/status overlap');assert.equal(m.halo,'none');
   const oldHeight=m.height<=500?210:Math.min(750,Math.max(170,m.height-410));assert(Math.abs(m.portrait.h-oldHeight*1.25)<1,'Shared portrait box must be 125%');
   if(url.includes('specialist=addie')||url.includes('specialist=oliver')){const enlarged=path.resolve(__dirname,'../evidence/specialist-enlargement-20260903');fs.mkdirSync(enlarged,{recursive:true});await page.screenshot({path:path.join(enlarged,`${url.includes('addie')?'addie':'oliver'}-${m.width}x${m.height}.png`),animations:'disabled'});}
  }
 }
 async function stableScreenshot(){let previous=null;for(let i=0;i<6;i++){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const current=await page.screenshot({animations:'disabled'});if(previous&&current.equals(previous))return current;previous=current;}throw Error('Screenshot did not stabilize');}
 async function geometry(){return page.evaluate(()=>[...document.querySelectorAll('.app-shell *')].filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{tag:e.tagName,id:e.id,x:r.x,y:r.y,w:r.width,h:r.height,font:s.font,color:s.color,display:s.display,transform:s.transform};}));}
 let worstRasterDifference=0;
 async function compareRaster(a,b){const [x,y]=await Promise.all([sharp(a).raw().toBuffer({resolveWithObject:true}),sharp(b).raw().toBuffer({resolveWithObject:true})]);assert.deepEqual(x.info,y.info);let changed=0;for(let i=0;i<x.data.length;i+=x.info.channels){let differs=false;for(let c=0;c<x.info.channels;c++)if(x.data[i+c]!==y.data[i+c])differs=true;if(differs)changed++;}const fraction=changed/(x.info.width*x.info.height);worstRasterDifference=Math.max(worstRasterDifference,fraction);assert(fraction<=.001,`Raster difference exceeds 0.1%: ${fraction}`);}
 await load('/?view=crew');assert.equal(await page.locator('[data-crew-id].roster-row').count(),9);
 for(const [id,name,role,asset] of expected){
  const card=page.locator(`.roster-row[data-crew-id="${id}"]`);await card.focus();await page.keyboard.press('Enter');
  assert.equal(await page.locator('#crew-detail-name').textContent(),name);assert(!await page.locator('#specialist-focus').evaluate(e=>e.open));
  const talk=page.getByRole('button',{name:`TALK TO ${name}`,exact:true});await talk.focus();await page.keyboard.press('Space');
  assert(await page.locator('#specialist-focus').evaluate(e=>e.open));assert.equal(await page.locator('#specialist-name').textContent(),name);assert.equal(await page.locator('#specialist-role').textContent(),role);assert((await page.locator('#specialist-portrait').getAttribute('src')).endsWith(asset));
  assert.equal(await page.locator('#specialist-connection').textContent(),'SPECIALIST VOICE — NOT YET CONNECTED');
  assert.equal(await page.locator('.specialist-voice-controls button:disabled').count(),4);
  await page.locator('.specialist-voice-controls button').evaluateAll(nodes=>nodes.forEach(n=>n.click()));
  assert(await page.locator('.home-view').evaluate(e=>e.inert||document.querySelector('#specialist-focus').matches(':modal')));
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'specialist-return-maeve');
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'specialist-return-crew');
  await page.getByRole('button',{name:'RETURN TO CREW',exact:true}).click();assert(!await page.locator('#specialist-focus').evaluate(e=>e.open));assert.equal(await page.locator('#crew-detail-name').textContent(),name);
  await talk.click();await page.getByRole('button',{name:'RETURN TO MAEVE',exact:true}).click();assert(await page.locator('.home-view').isVisible());assert(!await page.locator('#specialist-focus').evaluate(e=>e.open));assert.equal(await page.locator('#runtime-state').textContent(),'OFF');
  await page.locator('[data-view="crew"]').click();await page.getByRole('button',{name:'RETURN TO FULL ROSTER',exact:true}).click();
 }
 await load('/?view=crew');await page.locator('[data-crew-id="oliver"]').click();await page.evaluate(()=>document.body.dataset.voiceState='LISTENING');await page.locator('#specialist-talk').click();assert(!await page.locator('#specialist-focus').evaluate(e=>e.open));await page.evaluate(()=>document.body.dataset.voiceState='OFF');await page.locator('#specialist-talk').click();await page.keyboard.press('Escape');assert(!await page.locator('#specialist-focus').evaluate(e=>e.open));
 for(const id of ['operator','executor','unknown']){await load('/?specialist='+id);assert(!await page.locator('#specialist-focus').evaluate(e=>e.open));}
 const sizes=process.env.PHONE_DEBUG?[[430,932]]:[[2560,1440],[1920,1080],[1280,720],[430,932],[393,852],[932,430]];let mappingViews=0,preserved=0;
 for(const [width,height] of sizes){await page.setViewportSize({width,height});for(const [id] of expected){await load('/?specialist='+id);await page.locator('#specialist-portrait').evaluate(i=>i.decode());const bounds=await page.locator('#specialist-focus').evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));assert(bounds.scroll<=bounds.width,`${id} overflow ${width}`);for(const selector of ['#specialist-return-crew','#specialist-return-maeve','.specialist-voice-controls']){await page.locator(selector).scrollIntoViewIfNeeded();const b=await page.locator(selector).evaluate(e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:innerWidth,height:innerHeight,scroll:document.querySelector('#specialist-focus').scrollTop};});if(!(b.left>=0&&b.right<=width&&b.top>=0&&b.bottom<=height)){await page.screenshot({path:path.join(out,'clipped-debug.png')});console.log(b);}assert(b.left>=0&&b.right<=width&&b.top>=0&&b.bottom<=height,`${id} clipped ${selector} ${width}`);}mappingViews++;if(id==='oliver'){await page.locator('#specialist-focus').evaluate(e=>e.scrollTop=0);await page.screenshot({path:path.join(out,`oliver-${width}x${height}.png`)});}}
  for(const [url,clean] of [['/',false],['/',true],['/?focus=conversation',false],['/?view=crew',false]]){baseline=false;await load(url);if(clean)await page.evaluate(()=>MAEVE_INTEGRATED_UI.setCleanView(true));const after=await stableScreenshot(),afterGeometry=await geometry();baseline=true;await load(url);if(clean)await page.evaluate(()=>MAEVE_INTEGRATED_UI.setCleanView(true));const before=await stableScreenshot();assert.deepEqual(await geometry(),afterGeometry,`Approved geometry/style changed ${width} ${url}`);await compareRaster(after,before);preserved++;baseline=false;}
 }
 assert.equal(api,0);assert.equal(external,0);assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>window.audioRequests),0);
 const result={nineMappings:true,nineTalkButtons:true,returns:true,keyboard:true,disabledControls:true,unknownIdsRejected:true,activeSessionGuard:true,mappingViews,preservedViews:preserved,geometryAndStylesIdentical:true,worstRasterDifference,apiRequests:api,externalRequests:external,pageErrors:errors,microphoneAndPlaybackRequests:0};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
